### ISSUE TITLE
Keytool plugin is not threadSafe for maven parallel execution

### ISSUE THREAD

**Issue by Aellinsar** [mojohaus/keytool#11]
When executing maven in parallel using "mvn -T 4 install", the following warning is shown.

[DEBUG] =======================================================================
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
**[WARNING] The following goals are not marked @threadSafe in Certificates:
[WARNING] org.codehaus.mojo:keytool-maven-plugin:1.5:importCertificate**
[WARNING] *****************************************************************

**Comment by tchemit** [comment]
I will have a closer look to this issue, but using external tools inside this plugin may perhaps not make this possible.

**Comment by hiranchaudhuri1** [comment]
The external tool very likely limits parallel execution. Do the parallel executions all run in the same JVM? Then a synchronized method/section calling keytool would ensure only one of them runs at a time, and all the rest of the build could run in parallel. The warning would go away while consistency were preserved.

**Comment by bmarwell** [comment]
I uses the KeyTool classes from maven-shared-resources. They execute the keytool as an executable, always. I do not see why there would be a problem in executing those native processes in parallel.

IMHO, only  the threadsafe annotation is missing.

**Comment by tivervac** [comment]
@bmarwell Any idea when we can expect to see this in a new release? The latest release is from 2014

**Comment by bmarwell** [comment]
Not really. Locally I started a branch where I use the keytool API instead. :)

**Comment by tivervac** [comment]
@bmarwell I see that since then a new release came out, sadly it doesn't contain this fix. Could it be scheduled for the next one?
