### ISSUE TITLE
keytool:generateKeyPair can only take one <ext> configuration

### ISSUE THREAD

**Issue by soleger** [mojohaus/keytool#7]
It appears that it is legal to have multiple X.509 v3 extensions specified on the keytool command line (the `-ext` option). However, if you specify multiple `<ext>` tags in the configuration for the keytool:generateKeyPair command, it will only generate a `-ext` option for the final `<ext>` tag. This prevents you from specifying multiple extensions when using keytool:generateKeyPair.

**Comment by jlindholm** [comment]
looks like this was fixed?

**Comment by adamretter** [comment]
I am also experiencing this problem. I can send a PR...

**Comment by adamretter** [comment]
Looks like this was already fixed here - https://github.com/mojohaus/keytool/pull/8/
